In [ ]:
import os
import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
from google.colab import files
import pandas as pd


df = pd.read_csv('/content/AES_and_PRESENT_edges.csv')

In [ ]:
df.head()

   target  source
0       0       1
1       0       2
2       3       4
3       5       6
4       7       8

In [ ]:
# citations

In [ ]:
column_names = ["node_number"] + [f"term_{idx}" for idx in range(6)] + ["label"]
nodeset = pd.read_csv('/content/AES_and_PRESENT_nodeset')

In [ ]:
# nodeset = nodeset.drop(['Node'],axis=1)
# nodeset
nodeset = nodeset.rename(columns={"Unnamed: 0": "node_number"})
nodeset

,node_number,Node,Degree,and,or,mux,xor,label
0,0,AES_Comp_DEC.DC.SB0.Sbox3.AES_Comp_GFinvComp.1...,4,0,0,0,0,1
1,1,AES_Comp_DEC.DC.SB0.Sbox3.AES_Comp_GFinvComp.1...,3,0,0,0,0,1
2,2,AES_Comp_DEC.DC.SB0.Sbox3.AES_Comp_GFinvComp.1...,4,0,0,0,0,1
3,3,AES_Comp_DEC.DC.SB0.Sbox2.AES_Comp_GFinvComp.1...,3,0,0,0,0,1
4,4,AES_Comp_DEC.DC.SB0.Sbox2.AES_Comp_GFinvComp.1...,4,0,0,0,0,1
...,...,...,...,...,...,...,...,...
856,856,87:IF,3,0,0,0,0,0
857,857,88:NS,2,0,0,0,0,0
858,858,77:BL,2,0,0,0,0,0
859,859,USBOXKEY.194:CA,2,0,0,0,0,1
860,860,USBOX.191:BS,2,0,0,0,0,1

In [ ]:
hd1 = pd.read_csv("/content/final_hd_feature.csv")
hd1

     Hamming Distance
0                   0
1                   0
2                   0
3                   0
4                   0
..                ...
698                 0
699                46
700                44
701                 0
702                 0

[703 rows x 1 columns]

In [ ]:
hd2 = pd.read_csv("/content/PRESENT_hd_feature.csv")
hd2

     Hamming Distance
0               32661
1                   0
2                2027
3                2027
4               32661
..                ...
153             37786
154             37786
155                 0
156              2027
157                 0

[158 rows x 1 columns]

In [ ]:
hamming = pd.concat([hd1,hd2], ignore_index=True)
hamming

     Hamming Distance
0                   0
1                   0
2                   0
3                   0
4                   0
..                ...
856             37786
857             37786
858                 0
859              2027
860                 0

[861 rows x 1 columns]

In [ ]:
nodeset["Hamming distance"] = hamming
nodeset.head()

nodeset[702:-1]

,node_number,Node,Degree,and,or,mux,xor,label,Hamming distance
702,702,AES_Comp_DEC.DC.SB3.Sbox1.187:AS,3,0,0,0,0,1,0
703,703,UPBOX.161:AS,2,0,0,0,0,0,32661
704,704,76:AL,65,0,0,0,0,0,0
705,705,USBOXKEY.202:CA,2,0,0,0,0,1,2027
706,706,USBOXKEY.202:BS,2,0,0,0,0,1,2027
...,...,...,...,...,...,...,...,...,...
855,855,USBOXKEY.195:CA,2,0,0,0,0,1,32665
856,856,87:IF,3,0,0,0,0,0,37786
857,857,88:NS,2,0,0,0,0,0,37786
858,858,77:BL,2,0,0,0,0,0,0
859,859,USBOXKEY.194:CA,2,0,0,0,0,1,2027

In [ ]:
path1 = pd.read_csv("/content/paths_AES_comp.csv")
path2 = pd.read_csv("/content/PRESENT_paths.csv")
path2= path2.drop(['Unnamed: 0'],axis=1)
path2

     path
0       3
1       0
2       1
3       1
4       3
..    ...
153     0
154     0
155     0
156     1
157     3

[158 rows x 1 columns]

In [ ]:
path = pd.concat([path1,path2], ignore_index=True)
path

     path
0    6440
1    5152
2    5152
3    4830
4    6440
..    ...
856     0
857     0
858     0
859     1
860     3

[861 rows x 1 columns]

In [ ]:
nodeset["Paths"] = path
nodeset

,node_number,Node,Degree,and,or,mux,xor,label,Hamming distance,Paths
0,0,AES_Comp_DEC.DC.SB0.Sbox3.AES_Comp_GFinvComp.1...,4,0,0,0,0,1,0,6440
1,1,AES_Comp_DEC.DC.SB0.Sbox3.AES_Comp_GFinvComp.1...,3,0,0,0,0,1,0,5152
2,2,AES_Comp_DEC.DC.SB0.Sbox3.AES_Comp_GFinvComp.1...,4,0,0,0,0,1,0,5152
3,3,AES_Comp_DEC.DC.SB0.Sbox2.AES_Comp_GFinvComp.1...,3,0,0,0,0,1,0,4830
4,4,AES_Comp_DEC.DC.SB0.Sbox2.AES_Comp_GFinvComp.1...,4,0,0,0,0,1,0,6440
...,...,...,...,...,...,...,...,...,...,...
856,856,87:IF,3,0,0,0,0,0,37786,0
857,857,88:NS,2,0,0,0,0,0,37786,0
858,858,77:BL,2,0,0,0,0,0,0,0
859,859,USBOXKEY.194:CA,2,0,0,0,0,1,2027,1
860,860,USBOX.191:BS,2,0,0,0,0,1,0,3

In [ ]:
print(nodeset.label.value_counts())

1    702
0    159
Name: label, dtype: int64

In [ ]:
class_values = sorted(nodeset["label"].unique())
class_idx = {name: id for id, name in enumerate(class_values)}
paper_idx = {name: idx for idx, name in enumerate(sorted(nodeset["node_number"].unique()))}

nodeset["node_number"] = nodeset["node_number"].apply(lambda name: paper_idx[name])
df["source"] = df["source"].apply(lambda name: paper_idx[name])
df["target"] = df["target"].apply(lambda name: paper_idx[name])
nodeset["label"] = nodeset["label"].apply(lambda value: class_idx[value])
df

      target  source
0          0       1
1          0       2
2          3       4
3          5       6
4          7       8
...      ...     ...
1346     844     860
1347     841     709
1348     831     704
1349     847     848
1350     860     709

[1351 rows x 2 columns]

In [ ]:
train_data = nodeset.iloc[0:703]
test_data = nodeset.iloc[703:]

In [ ]:
test_data

,node_number,Node,Degree,and,or,mux,xor,label,Hamming distance,Paths
703,703,UPBOX.161:AS,2,0,0,0,0,0,32661,3
704,704,76:AL,65,0,0,0,0,0,0,0
705,705,USBOXKEY.202:CA,2,0,0,0,0,1,2027,1
706,706,USBOXKEY.202:BS,2,0,0,0,0,1,2027,1
707,707,UPBOX.149:AS,2,0,0,0,0,0,32661,3
...,...,...,...,...,...,...,...,...,...,...
856,856,87:IF,3,0,0,0,0,0,37786,0
857,857,88:NS,2,0,0,0,0,0,37786,0
858,858,77:BL,2,0,0,0,0,0,0,0
859,859,USBOXKEY.194:CA,2,0,0,0,0,1,2027,1
860,860,USBOX.191:BS,2,0,0,0,0,1,0,3

split on 1st graph

In [ ]:
train_data[train_data['and'] == 1]

,node_number,Node,Degree,and,or,mux,xor,label,Hamming distance,Paths
218,218,62:AS,4,1,1,0,0,0,0,0
229,229,61:AS,4,1,1,0,0,0,0,0
370,370,58:AS,1,1,0,0,0,0,1,0
438,438,65:AS,2,1,0,1,0,0,0,0
439,439,64:AS,2,1,0,1,0,0,0,0
515,515,57:AS,1,1,0,0,0,0,2,0

In [ ]:
hidden_units = [32, 32]
learning_rate = 0.0001
dropout_rate = 0.3
num_epochs = 32
batch_size = 20

In [ ]:
def run_experiment(model, x_train, y_train):
    # Compile the model.
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate),
        loss=keras.losses.BinaryCrossentropy(from_logits=False),
        metrics=[keras.metrics.BinaryAccuracy(name="acc"),
keras.metrics.Precision(), keras.metrics.Recall()],
    )
    # Create an early stopping callback.
    early_stopping = keras.callbacks.EarlyStopping(
        monitor="val_acc", patience=50, restore_best_weights=True
    )
    # Fit the model.
    history = model.fit(
        x=x_train,
        y=y_train,
        epochs=num_epochs,
        batch_size=batch_size,
        validation_split=0.10,
        callbacks=[early_stopping],
    )

    return history

In [ ]:
def display_learning_curves(history):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

    ax1.plot(history.history["loss"])
    ax1.plot(history.history["val_loss"])
    ax1.legend(["train", "test"], loc="upper right")
    ax1.set_xlabel("Epochs")
    ax1.set_ylabel("Loss")

    ax2.plot(history.history["acc"])
    ax2.plot(history.history["val_acc"])
    ax2.legend(["train", "test"], loc="upper right")
    ax2.set_xlabel("Epochs")
    ax2.set_ylabel("Accuracy")
    plt.show()

In [ ]:
def create_ffn(hidden_units, dropout_rate, name=None):
    fnn_layers = []

    for units in hidden_units:
        fnn_layers.append(layers.BatchNormalization())
        fnn_layers.append(layers.Dropout(dropout_rate))
        fnn_layers.append(layers.Dense(units, activation=tf.nn.relu))

    return keras.Sequential(fnn_layers, name=name)

In [ ]:
feature_names = set(nodeset.columns) - {"node_number","Node", "label"}
num_features = len(feature_names)
num_classes = len(class_idx)

print(train_data[feature_names])
# Create train and test features as a numpy array.
x_train = train_data[feature_names].to_numpy()
x_test = test_data[feature_names].to_numpy()
#print(x_train)
# Create train and test targets as a numpy array.
y_train = train_data["label"]
y_test = test_data["label"]

     Degree  and  Paths  or  xor  mux  Hamming distance
0         4    0   6440   0    0    0                 0
1         3    0   5152   0    0    0                 0
2         4    0   5152   0    0    0                 0
3         3    0   4830   0    0    0                 0
4         4    0   6440   0    0    0                 0
..      ...  ...    ...  ..  ...  ...               ...
698       3    0   2254   0    0    0                 0
699       3    0   2805   0    0    0                46
700       1    0   2793   0    0    0                44
701       3    0   7406   0    0    0                 0
702       3    0   7406   0    0    0                 0

[703 rows x 7 columns]

<ipython-input-50-09a25277351e>:5: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  print(train_data[feature_names])
<ipython-input-50-09a25277351e>:7: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  x_train = train_data[feature_names].to_numpy()
<ipython-input-50-09a25277351e>:8: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  x_test = test_data[feature_names].to_numpy()

In [ ]:
feature_names

{'Degree', 'Hamming distance', 'Paths', 'and', 'mux', 'or', 'xor'}

In [ ]:
def create_baseline_model(hidden_units, num_classes, dropout_rate=0.2):
    inputs = layers.Input(shape=(num_features,), name="input_features")
    x = create_ffn(hidden_units, dropout_rate, name=f"ffn_block1")(inputs)
    for block_idx in range(4):
        # Create an FFN block.
        x1 = create_ffn(hidden_units, dropout_rate, name=f"ffn_block{block_idx + 2}")(x)
        # Add skip connection.
        x = layers.Add(name=f"skip_connection{block_idx + 2}")([x, x1])
    # Compute logits.
    logits = layers.Dense(num_classes-1, name="logits")(x)
    # Create the model.
    return keras.Model(inputs=inputs, outputs=logits, name="baseline")


baseline_model = create_baseline_model(hidden_units, num_classes, dropout_rate)
baseline_model.summary()

Model: "baseline"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 input_features (InputLayer)    [(None, 7)]          0           []

 ffn_block1 (Sequential)        (None, 32)           1468        ['input_features[0][0]']

 ffn_block2 (Sequential)        (None, 32)           2368        ['ffn_block1[0][0]']

 skip_connection2 (Add)         (None, 32)           0           ['ffn_block1[0][0]',
                                                                  'ffn_block2[0][0]']

 ffn_block3 (Sequential)        (None, 32)           2368        ['skip_connection2[0][0]']

 skip_connection3 (Add)         (None, 32)           0           ['skip_connection2[0][0]',
                                                                  'ffn_block3[0][0]']

 ffn_block4 (Sequential)        (None, 32)           2368        ['skip_connection3[0][0]']

 skip_connection4 (Add)         (None, 32)           0           ['skip_connection3[0][0]',
                                                                  'ffn_block4[0][0]']

 ffn_block5 (Sequential)        (None, 32)           2368        ['skip_connection4[0][0]']

 skip_connection5 (Add)         (None, 32)           0           ['skip_connection4[0][0]',
                                                                  'ffn_block5[0][0]']

 logits (Dense)                 (None, 1)            33          ['skip_connection5[0][0]']

==================================================================================================
Total params: 10,973
Trainable params: 10,383
Non-trainable params: 590
__________________________________________________________________________________________________

In [ ]:
history = run_experiment(baseline_model, x_train, y_train)

In [ ]:
# Create an edges array (sparse adjacency matrix) of shape [2, num_edges].
edges = df[["source", "target"]].to_numpy().T
edge_weights = tf.ones(shape=edges.shape[1])

node_features = tf.cast(
    nodeset.sort_values("node_number")[feature_names].to_numpy(), dtype=tf.dtypes.float32
)
# Create graph with node features, edges, and edge_weights.
graph_info = (node_features, edges, edge_weights)

print("Edges shape:", edges.shape)
print("Nodes shape:", node_features.shape)
graph_info

Edges shape: (2, 1351)
Nodes shape: (861, 7)

<ipython-input-70-cae65ffcce56>:7: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  nodeset.sort_values("node_number")[feature_names].to_numpy(), dtype=tf.dtypes.float32

(<tf.Tensor: shape=(861, 7), dtype=float32, numpy=
 array([[4.000e+00, 0.000e+00, 6.440e+03, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [3.000e+00, 0.000e+00, 5.152e+03, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [4.000e+00, 0.000e+00, 5.152e+03, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        ...,
        [2.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [2.000e+00, 0.000e+00, 1.000e+00, ..., 0.000e+00, 0.000e+00,
         2.027e+03],
        [2.000e+00, 0.000e+00, 3.000e+00, ..., 0.000e+00, 0.000e+00,
         0.000e+00]], dtype=float32)>,
 array([[  1,   2,   4, ..., 704, 848, 709],
        [  0,   0,   3, ..., 831, 847, 860]]),
 <tf.Tensor: shape=(1351,), dtype=float32, numpy=array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)>)

In [ ]:
class GraphConvLayer(layers.Layer):
    def __init__(
        self,
        hidden_units,
        dropout_rate=0.3,
        aggregation_type="mean",
        combination_type="concat",
        normalize=False,
        *args,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)

        self.aggregation_type = aggregation_type
        self.combination_type = combination_type
        self.normalize = normalize

        self.ffn_prepare = create_ffn(hidden_units, dropout_rate)
        if self.combination_type == "gated":
            self.update_fn = layers.GRU(
                units=hidden_units,
                activation="tanh",
                recurrent_activation="sigmoid",
                dropout=dropout_rate,
                return_state=True,
                recurrent_dropout=dropout_rate,
            )
        else:
            self.update_fn = create_ffn(hidden_units, dropout_rate)

    def prepare(self, node_repesentations, weights=None):
        # node_repesentations shape is [num_edges, embedding_dim].
        messages = self.ffn_prepare(node_repesentations)
        if weights is not None:
            messages = messages * tf.expand_dims(weights, -1)
        return messages

    def aggregate(self, node_indices, neighbour_messages, node_repesentations):

        num_nodes = node_repesentations.shape[0]
        if self.aggregation_type == "sum":
            aggregated_message = tf.math.unsorted_segment_sum(
                neighbour_messages, node_indices, num_segments=num_nodes
            )
        elif self.aggregation_type == "mean":
            aggregated_message = tf.math.unsorted_segment_mean(
                neighbour_messages, node_indices, num_segments=num_nodes
            )
        elif self.aggregation_type == "max":
            aggregated_message = tf.math.unsorted_segment_max(
                neighbour_messages, node_indices, num_segments=num_nodes
            )
        else:
            raise ValueError(f"Invalid aggregation type: {self.aggregation_type}.")

        return aggregated_message

    def update(self, node_repesentations, aggregated_messages):

        if self.combination_type == "gru":
            # Create a sequence of two elements for the GRU layer.
            h = tf.stack([node_repesentations, aggregated_messages], axis=1)
        elif self.combination_type == "concat":
            # Concatenate the node_repesentations and aggregated_messages.
            h = tf.concat([node_repesentations, aggregated_messages], axis=1)
        elif self.combination_type == "add":
            # Add node_repesentations and aggregated_messages.
            h = node_repesentations + aggregated_messages
        else:
            raise ValueError(f"Invalid combination type: {self.combination_type}.")

        node_embeddings = self.update_fn(h)
        if self.combination_type == "gru":
            node_embeddings = tf.unstack(node_embeddings, axis=1)[-1]

        if self.normalize:
            node_embeddings = tf.nn.l2_normalize(node_embeddings, axis=-1)
        return node_embeddings

    def call(self, inputs):

        node_repesentations, edges, edge_weights = inputs

        node_indices, neighbour_indices = edges[0], edges[1]
        neighbour_repesentations = tf.gather(node_repesentations, neighbour_indices)
        neighbour_messages = self.prepare(neighbour_repesentations, edge_weights)

        aggregated_messages = self.aggregate(
            node_indices, neighbour_messages, node_repesentations
        )

        return self.update(node_repesentations, aggregated_messages)

In [ ]:
class GNNNodeClassifier(tf.keras.Model):
    def __init__(
        self,
        graph_info,
        num_classes,
        hidden_units,
        aggregation_type="sum",
        combination_type="concat",
        dropout_rate=0.3,
        normalize=True,
        *args,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)

        # Unpack graph_info to three elements: node_features, edges, and edge_weight.
        node_features, edges, edge_weights = graph_info
        self.node_features = node_features
        self.edges = edges
        self.edge_weights = edge_weights
        # Set edge_weights to ones if not provided.
        if self.edge_weights is None:
            self.edge_weights = tf.ones(shape=edges.shape[1])
        # Scale edge_weights to sum to 1.
        self.edge_weights = self.edge_weights / tf.math.reduce_sum(self.edge_weights)

        # Create a process layer.
        self.preprocess = create_ffn(hidden_units, dropout_rate, name="preprocess")
        # Create the first GraphConv layer.
        self.conv1 = GraphConvLayer(
            hidden_units,
            dropout_rate,
            aggregation_type,
            combination_type,
            normalize,
            name="graph_conv1",
        )
        # Create the second GraphConv layer.
        self.conv2 = GraphConvLayer(
            hidden_units,
            dropout_rate,
            aggregation_type,
            combination_type,
            normalize,
            name="graph_conv2",
        )
        # Create a postprocess layer.
        self.postprocess = create_ffn(hidden_units, dropout_rate, name="postprocess")
        # Create a compute logits layer.
        self.compute_logits = layers.Dense(units=num_classes,activation="softmax", name="logits")

    def call(self, input_node_indices):
        # Preprocess the node_features to produce node representations.
        x = self.preprocess(self.node_features)
        # Apply the first graph conv layer.
        x1 = self.conv1((x, self.edges, self.edge_weights))
        # Skip connection.
        x = x1 + x
        # Apply the second graph conv layer.
        x2 = self.conv2((x, self.edges, self.edge_weights))
        # Skip connection.
        x = x2 + x
        # Postprocess node embedding.
        x = self.postprocess(x)
        # Fetch node embeddings for the input node_indices.
        node_embeddings = tf.gather(x, input_node_indices)
        print(node_embeddings)
        # Compute logits
        return self.compute_logits(node_embeddings)

In [ ]:
gnn_model = GNNNodeClassifier(
    graph_info=graph_info,
    num_classes=num_classes,
    hidden_units=hidden_units,
    dropout_rate=dropout_rate,
    name="gnn_model",
)

print("GNN output shape:", gnn_model([1, 10, 100]))

gnn_model.summary()

tf.Tensor(
[[5.21333618e+02 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 1.06415733e+02 0.00000000e+00 1.03273071e+02
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 4.80887817e+02 4.06951843e+02 0.00000000e+00
  0.00000000e+00 7.71088196e+02 1.08706894e+02 1.14647074e+01
  0.00000000e+00 5.89831787e+02 3.44203796e+01 1.17494148e+02
  0.00000000e+00 0.00000000e+00 7.60481644e+01 0.00000000e+00
  4.28732086e+02 1.53934240e+01 3.60907379e+02 5.72000771e+01]
 [9.59850997e-02 2.37541705e-01 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 9.05852467e-02
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  5.06232083e-02 3.51755321e-01 3.17057580e-01 0.00000000e+00
  1.60343647e-01 4.52740878e-01 9.65995342e-02 0.00000000e+00
  0.00000000e+00 2.63843566e-01 0.00000000e+00 3.97367746e-01
  0.00000000e+00 0.00000000e+00 2.36105382e-01 6.74989121e-03
  3.58940870e-01 0.00000000e+00 3.91475677e-01 0.00000000e+00]
 [7.49378479e+02 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 1.53033340e+02 0.00000000e+00 1.48430923e+02
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 6.91074097e+02 5.84770325e+02 0.00000000e+00
  0.00000000e+00 1.10848511e+03 1.56312622e+02 1.64927940e+01
  0.00000000e+00 8.47934814e+02 4.95667648e+01 1.68621628e+02
  0.00000000e+00 0.00000000e+00 1.09160706e+02 0.00000000e+00
  6.16405029e+02 2.22758484e+01 5.18770935e+02 8.23525925e+01]], shape=(3, 32), dtype=float32)
GNN output shape: tf.Tensor(
[[1.0000000e+00 7.5241492e-34]
 [5.4330140e-01 4.5669863e-01]
 [1.0000000e+00 0.0000000e+00]], shape=(3, 2), dtype=float32)
Model: "gnn_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 preprocess (Sequential)     (861, 32)                 1468

 graph_conv1 (GraphConvLayer  multiple                 5888
 )

 graph_conv2 (GraphConvLayer  multiple                 5888
 )

 postprocess (Sequential)    (861, 32)                 2368

 logits (Dense)              multiple                  66

=================================================================
Total params: 15,678
Trainable params: 14,832
Non-trainable params: 846
_________________________________________________________________

In [ ]:
y_train1 = tf.keras.utils.to_categorical(
    y_train, num_classes=2, dtype='float32')
y_test1 = tf.keras.utils.to_categorical(
    y_test, num_classes=2, dtype='float32')
# y_train1[:10],y_train.value_counts()

In [ ]:
x_train = train_data.node_number.to_numpy()
history = run_experiment(gnn_model, x_train, y_train1)

Epoch 1/32
Tensor("gnn_model/GatherV2:0", shape=(None, 32), dtype=float32)
Tensor("gnn_model/GatherV2:0", shape=(None, 32), dtype=float32)
32/32 [==============================] - ETA: 0s - loss: 0.7418 - acc: 0.5839 - precision_2: 0.5839 - recall_2: 0.5839Tensor("gnn_model/GatherV2:0", shape=(None, 32), dtype=float32)
32/32 [==============================] - 39s 129ms/step - loss: 0.7418 - acc: 0.5839 - precision_2: 0.5839 - recall_2: 0.5839 - val_loss: 0.7128 - val_acc: 0.3662 - val_precision_2: 0.3662 - val_recall_2: 0.3662
Epoch 2/32
32/32 [==============================] - 3s 80ms/step - loss: 0.7375 - acc: 0.6092 - precision_2: 0.6092 - recall_2: 0.6092 - val_loss: 0.6932 - val_acc: 0.5634 - val_precision_2: 0.5634 - val_recall_2: 0.5634
Epoch 3/32
32/32 [==============================] - 3s 91ms/step - loss: 0.6718 - acc: 0.6804 - precision_2: 0.6804 - recall_2: 0.6804 - val_loss: 0.6757 - val_acc: 0.7324 - val_precision_2: 0.7324 - val_recall_2: 0.7324
Epoch 4/32
32/32 [==============================] - 4s 116ms/step - loss: 0.6508 - acc: 0.7247 - precision_2: 0.7247 - recall_2: 0.7247 - val_loss: 0.6711 - val_acc: 0.7887 - val_precision_2: 0.7887 - val_recall_2: 0.7887
Epoch 5/32
32/32 [==============================] - 3s 100ms/step - loss: 0.6387 - acc: 0.7405 - precision_2: 0.7405 - recall_2: 0.7405 - val_loss: 0.6667 - val_acc: 0.8592 - val_precision_2: 0.8592 - val_recall_2: 0.8592
Epoch 6/32
32/32 [==============================] - 2s 55ms/step - loss: 0.6127 - acc: 0.7880 - precision_2: 0.7880 - recall_2: 0.7880 - val_loss: 0.6533 - val_acc: 0.7887 - val_precision_2: 0.7887 - val_recall_2: 0.7887
Epoch 7/32
32/32 [==============================] - 2s 61ms/step - loss: 0.6256 - acc: 0.7753 - precision_2: 0.7753 - recall_2: 0.7753 - val_loss: 0.6338 - val_acc: 0.8592 - val_precision_2: 0.8592 - val_recall_2: 0.8592
Epoch 8/32
32/32 [==============================] - 2s 60ms/step - loss: 0.5866 - acc: 0.7991 - precision_2: 0.7991 - recall_2: 0.7991 - val_loss: 0.6102 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 9/32
32/32 [==============================] - 2s 51ms/step - loss: 0.5802 - acc: 0.8228 - precision_2: 0.8228 - recall_2: 0.8228 - val_loss: 0.5803 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 10/32
32/32 [==============================] - 2s 63ms/step - loss: 0.5426 - acc: 0.8434 - precision_2: 0.8434 - recall_2: 0.8434 - val_loss: 0.5430 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 11/32
32/32 [==============================] - 2s 72ms/step - loss: 0.5415 - acc: 0.8623 - precision_2: 0.8623 - recall_2: 0.8623 - val_loss: 0.5079 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 12/32
32/32 [==============================] - 2s 70ms/step - loss: 0.5102 - acc: 0.8734 - precision_2: 0.8734 - recall_2: 0.8734 - val_loss: 0.4809 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 13/32
32/32 [==============================] - 2s 54ms/step - loss: 0.4866 - acc: 0.8687 - precision_2: 0.8687 - recall_2: 0.8687 - val_loss: 0.4551 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 14/32
32/32 [==============================] - 2s 54ms/step - loss: 0.4561 - acc: 0.8766 - precision_2: 0.8766 - recall_2: 0.8766 - val_loss: 0.4363 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 15/32
32/32 [==============================] - 2s 65ms/step - loss: 0.4480 - acc: 0.8924 - precision_2: 0.8924 - recall_2: 0.8924 - val_loss: 0.4164 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 16/32
32/32 [==============================] - 2s 61ms/step - loss: 0.4373 - acc: 0.8972 - precision_2: 0.8972 - recall_2: 0.8972 - val_loss: 0.3875 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 17/32
32/32 [==============================] - 1s 32ms/step - loss: 0.4318 - acc: 0.8940 - precision_2: 0.8940 - recall_2: 0.8940 - val_loss: 0.3558 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 18/32
32/32 [==============================] - 1s 30ms/step - loss: 0.4205 - acc: 0.8877 - precision_2: 0.8877 - recall_2: 0.8877 - val_loss: 0.3299 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 19/32
32/32 [==============================] - 1s 37ms/step - loss: 0.4295 - acc: 0.9066 - precision_2: 0.9066 - recall_2: 0.9066 - val_loss: 0.3128 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 20/32
32/32 [==============================] - 2s 48ms/step - loss: 0.4138 - acc: 0.9035 - precision_2: 0.9035 - recall_2: 0.9035 - val_loss: 0.3017 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 21/32
32/32 [==============================] - 2s 61ms/step - loss: 0.3642 - acc: 0.9161 - precision_2: 0.9161 - recall_2: 0.9161 - val_loss: 0.2946 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 22/32
32/32 [==============================] - 3s 90ms/step - loss: 0.4017 - acc: 0.9035 - precision_2: 0.9035 - recall_2: 0.9035 - val_loss: 0.2802 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 23/32
32/32 [==============================] - 2s 68ms/step - loss: 0.3653 - acc: 0.9035 - precision_2: 0.9035 - recall_2: 0.9035 - val_loss: 0.2737 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 24/32
32/32 [==============================] - 2s 59ms/step - loss: 0.3558 - acc: 0.9051 - precision_2: 0.9051 - recall_2: 0.9051 - val_loss: 0.2663 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 25/32
32/32 [==============================] - 2s 55ms/step - loss: 0.3600 - acc: 0.9082 - precision_2: 0.9082 - recall_2: 0.9082 - val_loss: 0.2550 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 26/32
32/32 [==============================] - 2s 50ms/step - loss: 0.3678 - acc: 0.9082 - precision_2: 0.9082 - recall_2: 0.9082 - val_loss: 0.2466 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 27/32
32/32 [==============================] - 2s 53ms/step - loss: 0.3328 - acc: 0.9035 - precision_2: 0.9035 - recall_2: 0.9035 - val_loss: 0.2402 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 28/32
32/32 [==============================] - 2s 74ms/step - loss: 0.3316 - acc: 0.9019 - precision_2: 0.9019 - recall_2: 0.9019 - val_loss: 0.2348 - val_acc: 0.9437 - val_precision_2: 0.9437 - val_recall_2: 0.9437
Epoch 29/32
32/32 [==============================] - 2s 71ms/step - loss: 0.3258 - acc: 0.9114 - precision_2: 0.9114 - recall_2: 0.9114 - val_loss: 0.2254 - val_acc: 0.9296 - val_precision_2: 0.9296 - val_recall_2: 0.9296
Epoch 30/32
32/32 [==============================] - 2s 66ms/step - loss: 0.3223 - acc: 0.9082 - precision_2: 0.9082 - recall_2: 0.9082 - val_loss: 0.2197 - val_acc: 0.9296 - val_precision_2: 0.9296 - val_recall_2: 0.9296
Epoch 31/32
32/32 [==============================] - 2s 63ms/step - loss: 0.3001 - acc: 0.9193 - precision_2: 0.9193 - recall_2: 0.9193 - val_loss: 0.2177 - val_acc: 0.9296 - val_precision_2: 0.9296 - val_recall_2: 0.9296
Epoch 32/32
32/32 [==============================] - 2s 49ms/step - loss: 0.3347 - acc: 0.9066 - precision_2: 0.9066 - recall_2: 0.9066 - val_loss: 0.2135 - val_acc: 0.9296 - val_precision_2: 0.9296 - val_recall_2: 0.9296

In [ ]:
gnn_model.save_weights('/content/saved_weights')

check

In [ ]:
# model = keras.models.load_model("/content/gnn_model")
model = GNNNodeClassifier(
    graph_info=graph_info,
    num_classes=num_classes,
    hidden_units=hidden_units,
    dropout_rate=dropout_rate,
    name="gnn_model",
)
model.load_weights('/content/saved_weights')

In [ ]:
from keras import backend as K
model.compile()
x_test = test_data.node_number.to_numpy()
_, test_accuracy, precision, recall = gnn_model.evaluate(x=x_test, y=y_test1, verbose=0)
print(f"Test accuracy: {round(test_accuracy * 100, 2)}%")
print(f"Test precision: {(precision* 100)}%")
print(f"Test recall: {(recall * 100)}%")

Test accuracy: 88.61%
Test precision: 88.60759735107422%
Test recall: 88.60759735107422%

when 80-20 is used

In [ ]:
# y_pred = gnn_model.predict(new_xtest)
# print(classification_report(new_ytest1,y_pred))
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred= gnn_model.predict(new_xtest)
y_pred = np.argmax(y_pred, axis=1)
y_testt = np.argmax(new_ytest1, axis=1)
cm = confusion_matrix(y_testt, y_pred)
print(cm)
print(classification_report(y_testt,y_pred))

Tensor("gnn_model/GatherV2:0", shape=(None, 32), dtype=float32)
5/5 [==============================] - 4s 17ms/step
[[74 14]
 [ 4 66]]
              precision    recall  f1-score   support

           0       0.95      0.84      0.89        88
           1       0.82      0.94      0.88        70

    accuracy                           0.89       158
   macro avg       0.89      0.89      0.89       158
weighted avg       0.89      0.89      0.89       158